version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "golek_rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq/mnesia
      - ./rabbitmq/log/:/var/log/rabbitmq/
    networks:
      default:
        ipv4_address: 172.53.1.10

networks:
  default:
    name: golek_network_br
    external: true
